title: Disha Balpande # your name (or website title) here
logo: "/images/Disha_profile.png?raw=true" # your photo (or logo) here
description:  # your text below (remove <br> elements if you don't need line breaks)
 M-Tech |  Data Science Practitioner 
  <br><br>
  
  
  
  <p>
  <a href="https://www.linkedin.com/in/dishabalpande/">
  <img border="0" alt="LinkedIn" src="/images/linkedin_logo.png" width="35" height="35">
  </a>
  
  <a href="https://github.com/DishaBalpande">
  <img border="0" alt="Github" src="/images/github_logo.png" width="35" height="35">
  </a>
  
  <a href="https://medium.com/@DishaBalpande">
  <img border="0" alt="Medium" src="/images/medium_logo.png" width="35" height="35">
  </a> 
  
  <a href="mailto:disha24balpande@gmail.com">
  <img border="0" alt="Gmail" src="/images/gmail_logo.png" width="35" height="35">
  </a>
  
  <a href="https://twitter.com/BalpandeDisha?s=09">
  <img border="0" alt="Twitter" src="/images/twitter_logo.png" width="35" height="35">
  </a>
  </p>
  
    
  <p>
  <a href="Disha_Balpande_CV.pdf" download="Disha Balpande.pdf">
    <button>Download CV</button>
  </a>
  <a href="/contact.html" >
    <button>Contact Me</button>
    </a>
  </p>





  
  
  
  
   
  
  

